"""
config.py — Cadodile Trivia Quest Configuration
"""

# ── Hardware Pins ──
LED_GPIO = 18
SERVO_CHANNEL = 0

# ── Servo Angles ──
SERVO_CENTER = 90
DISPENSE_OPEN_ANGLE = 140
DISPENSE_CLOSED_ANGLE = 40
DISPENSE_OPEN_TIME_SEC = 0.6
DISPENSE_PAUSE_SEC = 0.2

# ── Game Settings ──
QUESTIONS_PER_GAME = 10
MAX_PLAYERS = 4

# ── UI Colors ──
COLOR_BG_DARK = "#2a4a7f"
COLOR_BG_MID = "#3561a8"
COLOR_BG_LIGHT = "#4178c4"
COLOR_ACCENT = "#e94560"
COLOR_ACCENT_DARK = "#c23152"
COLOR_ACCENT_GOLD = "#fbbf24"
COLOR_TEXT_LIGHT = "#ffffff"
COLOR_TEXT_DARK = "#1a1a2e"
COLOR_CORRECT = "#4ade80"
COLOR_WRONG = "#ef4444"
COLOR_BUTTON = "#3b82f6"
COLOR_BUTTON_HOVER = "#2563eb"
COLOR_GRASS = "#4ade80"
COLOR_GRASS_DARK = "#22c55e"
COLOR_DIRT = "#b45309"
COLOR_DIRT_DARK = "#92400e"
COLOR_BRICK = "#ef4444"
COLOR_COIN = "#fbbf24"
COLOR_PIPE_GREEN = "#22c55e"
COLOR_STAR = "#fde047"

# ── UI Sizes ──
FONT_SIZE_TITLE = 42
FONT_SIZE_HEADING = 28
FONT_SIZE_BODY = 20
FONT_SIZE_BUTTON = 24
BUTTON_HEIGHT = 62
BUTTON_RADIUS = 12

# ── Display ──
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 1024
SCREEN_ORIENTATION = "vertical"

# ── Language ──
DEFAULT_LANGUAGE = "en"
